"""empty message

Revision ID: 294ee0307d91
Revises: b40fac9b850c
Create Date: 2021-02-24 12:33:37.949654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '294ee0307d91'
down_revision = 'b40fac9b850c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('candidate', 'department_ID',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('candidate', 'full_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('candidate', 'resume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_index('years_of_experience', table_name='candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('years_of_experience', 'candidate', ['years_of_experience'], unique=True)
    op.alter_column('candidate', 'resume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('candidate', 'full_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('candidate', 'department_ID',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('candidate', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
