"""empty message

Revision ID: f1b01efe0391
Revises: 294ee0307d91
Create Date: 2021-02-24 12:34:50.961101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1b01efe0391'
down_revision = '294ee0307d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('candidate', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('candidate', 'department_ID',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('candidate', 'full_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('candidate', 'resume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('candidate', 'years_of_experience',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'years_of_experience',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('candidate', 'resume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('candidate', 'full_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('candidate', 'department_ID',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('candidate', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('candidate', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
